server:
  port: 5008
spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:itachi #can spcify login credentials here, lives at http://localhost:5004/h2-console
    #platform: postgresql
    #url: jdbc:postgresql://localhost:3001/itachi
    #username: itachi
    #password: itachi

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:3001/ekart
    username: itachi
    password: itachi
    pool-size: 30
